name: stylelint

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm install
      - name: Run Stylelint
        run: npm run lint
